spring:
  datasource:
    name: car
    url: jdbc:mysql://localhost:3306/car#url
    username: root
    password: 1122
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mybatis/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.example.car
